"""
Teste
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_1")
def python_1_func():
    print("teste número 1")

default_args={
    "owner": "Guilherme Roca,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2025-02-03", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Guilherme Roca": "mailto:guiroca@gmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm6p50iq2180m01iv0u9abvql/cloud-ide/cm6p57xm0182301ivk13jjte9/cm6p5fvmp183n01ivgh6lsnuc",
    },
)
def Teste():
    python_1 = python_1_func()

dag_obj = Teste()
